### ISSUE TITLE
request to register "cite-as" link relation type

### ISSUE THREAD

**Issue by hvdsomp** [link-relations/registry#1]
Enter the details of the link relation type below:

* Relation Name: cite-as
* Description: A link with the "cite-as" relation type indicates that the link target is preferred over the link context for the purpose of referencing.
* Reference: Van de Sompel, H., Nelson, M.L., Bilder, G., Kunze, J., and Warner, S. (August 2017) cite-as: A Link Relation to Convey a Preferred URI for Referencing. https://datatracker.ietf.org/doc/draft-vandesompel-citeas/

Any additional information (this will not be included in the registry)?

This request to register "cite-as" is the result of a prior attempt to register "identifier". Significant concerns were voiced regarding "identifier" and, as a result, the co-authors of the I-D decided to settle on "cite-as", which was proposed during the discussions of "identifier".

The request to register "cite-as" on the basis of ID-00 is motivated by ongoing adoption of various patterns for using link relation types in scholarly communication, see http://signposting.org. As soon as "cite-as" is registered:

- Existing implementations will be asked to change their use of "identifier" to "cite-as"

- Documentation will be updated to reflect the change from "identifier" to "cite-as" at http://signposting.org/identifier/

**Comment by mnot** [comment]
Approved; IANA request made. Please stand by, as we're still working out the kinks.

**Comment by hvdsomp** [comment]
On Oct 25, 2017, at 21:24, Mark Nottingham <notifications@github.com> wrote:
> 
> Approved; IANA request made.
> 
Thanks!!!
> Please stand by, as we're still working out the kinks.
> 
Talking about The Kinks: I saw them live in 1970 at Jazz Bilzen in Belgium. I was 13; my brother snuck me in because I was such a massive fan. There’s this timepiece video from Belgian TV: https://m.youtube.com/watch?v=2V6LMhzWDiY My brother enters the scene at 1:28, The Kinks at 20:10.  Sorry but I couldn’t keep myself. 

Cheers

Herbert
