### ISSUE TITLE
manifest

### ISSUE THREAD

**Issue by mnot** [link-relations/registry#14]
* Relation Name: manifest
* Description: links to a manifest file for the context
* Reference: https://www.w3.org/TR/appmanifest/#using-a-link-element-to-link-to-a-manifest

**Comment by mnot** [comment]
@marcoscaceres please review?

**Comment by marcoscaceres** [comment]
Looks good :)

**Comment by mnot** [comment]
Thanks, Marcos. I updated the reference to use the TR link.

**Comment by dr-shorthair** [comment]
The Web App Manifest is a clearly specified link in the context of web applications. However, there may be other contexts within which a link to an inventory or manifest is useful - for example the [Profile vocabulary](https://raw.githack.com/w3c/dxwg/prof-3PWD-candidate/prof/#conceptualmodel) currently under development by the W3C Data Exchange Working Group defines what is essentially a manifest for the description of a data standard. 

Would this registration essentially quarantine the `manifest` link for only the web application context?

**Comment by marcoscaceres** [comment]
> Would this registration essentially quarantine the manifest link for only the web application context?

Yes. We are claiming that relation name to mean something very specific - and with very specific processing requirements (per the web manifest spec).
