### ISSUE TITLE
New Google relations in the wild

### ISSUE THREAD

**Issue by mnot** [link-relations/registry#15]
`ugc` and `sponsored`. See https://webmasters.googleblog.com/2019/09/evolving-nofollow-new-ways-to-identify.html

**Comment by mnot** [comment]
Proposal:

* Relation Name: ugc
* Description: Refers to a resource that is within a context that is User Generated Content.
* Reference: https://webmasters.googleblog.com/2019/09/evolving-nofollow-new-ways-to-identify.html

and

* Relation Name: sponsored
* Description: Refers to a resource that is within a context that is sponsored (such as advertising or another compensation agreement).
* Reference: https://webmasters.googleblog.com/2019/09/evolving-nofollow-new-ways-to-identify.html

**Comment by mnot** [comment]
@garyillyes do these look reasonable?

**Comment by garyillyes** [comment]
yup! sorry, i wasn't aware of this registry when we announced these new rels
