### ISSUE TITLE
request to register "conformance", "data", "items"

### ISSUE THREAD

**Issue by cportele** [link-relations/registry#17]
Enter the details of the link relation type below:

1.
* Relation Name: conformance
* Description: Refers to a resource that identifies the specifications that the link’s context conforms to.
* Reference: [OGC API - Features - Part 1: Core, 5.2. Link relations](http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_link_relations)

2.
* Relation Name: data
* Description:  Indicates that the link’s context is a distribution of a dataset that is an API and refers to the root resource of the dataset in the API.
* Reference: [OGC API - Features - Part 1: Core, 5.2. Link relations](http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_link_relations)

3.
* Relation Name: items
* Description: Refers to a resource that is comprised of members of the collection represented by the link’s context.
* Reference: [OGC API - Features - Part 1: Core, 5.2. Link relations](http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_link_relations)

Any additional information (this will not be included in the registry)?

The link relation types are used in a Web API standard of the [Open Geospatial Consortium (OGC)](https://www.opengeospatial.org/). We have tried to re-use existing link relation types, where possible, but had to define three new types. We have tried to phrase the definitions in a general way so that they could be useful for other contexts, too.

* An example for the use of `conformance` and `data`: [link](http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#example_2)
* An example for the use of `items`: [link](http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#example_4)

**Comment by algermissen** [comment]
Hi Clemens,

I'd say there is some overlap with https://tools.ietf.org/html/rfc6573  wrt 'items'

What do you think?

Jan

**Comment by cportele** [comment]
Hi Jan,

the standard is also using both `item` and `collection`. The reason for `items` is that between the collection resource and the item resources we have an intermediate items resource that gives paged access to all items in the collection. The reason for not including the items in the collection resource representation is that there are often many of them (thousands / millions) and it is useful to have summary information about the items in the collection resource, but to have a separate resource that represents all the items in the collection. A sample use case is a dataset of buildings. The collection resource will have a description, the spatial and temporal extent of the data, etc. The items resource (linked from the collection resource using `rel=items` ) will return all buildings (with pagination) and will be used, for example, by applications that render buildings on a map. There is also an item resource for each building so that one can link to an indivdual building.

Does this help?

Thanks,
Clemens

**Comment by evert** [comment]
’data‘ seems like a very generic keyword for such a specific purpose. After all, everything is data.

**Comment by reschke** [comment]
On 28.11.2019 14:14, Evert Pot wrote:
> ’data‘ seems like a very generic keyword for such a specific purpose.
> After all, everything is data.
> ...

+1000

**Comment by cportele** [comment]
I see the point. I guess we should then drop this one for now and consider changing it to a more specific name in a future revision of the spec.

**Comment by mnot** [comment]
H @cportele, 

As others have noticed, these are very generic terms. Generally, we avoid using generic terms defined for specific applications; even if the description is broad, people tend to assume that being defined as part of a narrow specification (like OGC) restricts them to that use.

Because of that, I think there are two possible paths forward:

1. Extract these relation types from this specification and define them in a standalone spec that has review exposure to a wider community (e.g., an RFC or a W3C Recommendation), or

2. Rename these types to be more specific; e.g., `ogc-conformance`, `ogc-data`, and `ogc-items`.

Cheers,

**Comment by cportele** [comment]
Thanks for the feedback. I will take the discussion on the way forward back to OGC and closes this here.
