### ISSUE TITLE
Request to register: `news`

### ISSUE THREAD

**Issue by ronaldtse** [link-relations/registry#2]
Enter the details of the link relation type below:

* Relation Name: `news`
* Description: This link provides news on the subject itself. No restrictions are placed on the content of the destination link; its contents may be structured (RSS/Atom) or unstructured.
* Reference: None yet -- if a draft is necessary we can write one 😉 

Any additional information (this will not be included in the registry)?

For example, the link 
`https://www.iso.org/contents/data/standard/07/39/73906.detail.rss`
provides updates to the ISO/IEC 27001 standard (about page: https://www.iso.org/standard/73906.html).

**Comment by mnot** [comment]
Hi,

Sorry for the delay; IETF London got in the way.

A specification reference is required; best is an RFC or a W3C document, but something published by another organisation is fine, as long as it's stable. Do you have somewhere to do that?

Regarding the description:

> This link provides news on the subject itself. No restrictions are placed on the content of the destination link; its contents may be structured (RSS/Atom) or unstructured.

Link relations can't disallow content, so the phrase at the end is superfluous. I'd recommend:

> The link target is news or updates about the link context.

Does that work for you?

Looking through the already registered link relations, there are a few generic ones that could be used for the purpose you want, but they aren't as specific as this one. The only one that comes close is `monitor` -- but that doesn't preclude registration here (as that seems more like a protocol-specific relation). Just wanted to make sure you're aware of it.

**Comment by mnot** [comment]
No response, so closing. Please feel free to supply the requested information and we'll reconsider.
