### ISSUE TITLE
Request to register ‘tor’

### ISSUE THREAD

**Issue by cguess** [link-relations/registry#3]
Enter the details of the link relation type below:

* Relation Name: ‘tor’
* Description: Many organizations are beginning to offer hosted services and web sites that are only accessible via the TOR network. These TOR hidden services usually offer mirrored versions of the company’s products, but with the added benefit of anonymity of the user. These services can also often be accessed even in the case of censorship or blocking of the parent “open-web” site by state or telecom powers.

However, discovering which sites offer TOR alternatives, much less what the TOR URL even is, can be daunting and difficult. While the point of some .onion web addresses is security through anonymity, many of these sorts of sites are not. The companies themselves often highlight their offerings in blog posts and aggregate lists do exist for some services. Up to this point though there is no way to publish this standardized way; for instance, in a manner where canonical lists could be automatically generated and built into the TOR browser or other anti-censorship tools.

Allowing web-masters to publicize their TOR alternatives would allow tools to automatically redirect instead of ever accessing the open web, increasing security and anonymity with no extra work by the end user.

* Reference: No written references but implementation details follow:

Href links should be canonical to the current web address. For instance, the tag on a home page for the OCCRP organization at https://www.occrp.org would be:
<link rel="tor" href="http://occrpweb4n2vlmih.onion" />

For a subdirectory https://www.occrp.org/en/azerbaijanilaudromat: 
<link rel="tor" href="http://occrpweb4n2vlmih.onion/en/azerbaijanilaundromat/" />

Any additional information (this will not be included in the registry)?

No

**Comment by mnot** [comment]
Hi,

A reference is required for registration. Ideally that would be an RFC or W3C document, but something hosted by another organisation would also work, provided it's a stable URL. 

Here, the most logical place would be somewhere on https://www.torproject.org/  

If you haven't already, I'd recommend starting a discussion in the Tor community to make sure that there's agreement there about how to do this. 

A couple of other recommendations:

* The relation name is pretty generic; have you considered something more specific, like `tor-hidden-service`?

* The description listed is pretty long; generally we look for something like this:

> The link target is an alternative for the current context, as a Tor hidden service.

BTW, it looks like some of the text you entered above was lost.

/cc @nmathewson @mikeperry-tor

**Comment by mnot** [comment]
No response, so closing. Please feel free to supply the requested information and we'll close.
