### ISSUE TITLE
Temporal interval relation: intervalAfter

### ISSUE THREAD

**Issue by dr-shorthair** [link-relations/registry#4]
Enter the details of the link relation type below:

* Relation Name: intervalAfter
* Description: If a proper interval T1 is intervalAfter another proper interval T2, then the beginning of T1 is after the end of T2.
* Reference: [W3C OWL-Time clause 4.2.21](https://www.w3.org/TR/owl-time/#time:intervalAfter)

Any additional information (this will not be included in the registry)? 

This is one of a set of 15 interval relations which have been adapted from Allen's work, and formalized in the [W3C OWL-Time ontology](https://www.w3.org/TR/owl-time/): 

![interval relations](https://www.w3.org/TR/owl-time/images/IntervalRelations.png)

I will refrain from submitting separate issue for the other 14 until this one has been commented on ;-)

**Comment by reschke** [comment]
The description ought to be useful to somebody who doesn't know the spec...

**Comment by algermissen** [comment]
Do I understand this correctly, you are about to use the IANA link relation registry to define the semantics of the world based on OWL?

Three questions:

What is the use case you have in mind for eg temporal relationships expressed as hypermedia links?

Where will you stop? Is the scope only the temporal rels? If so, why only those?

Last time I checked RDF hat all the proper ecosystem in place for establishing semantics via RDF properties. Why not just use that ecosystem and all its tooling?

Jan

**Comment by dr-shorthair** [comment]
@reschke The description is an extract from the spec, but I think it is logically and mathematically correct and can stand alone. I've added the key diagram as well - is this better? 

@algermissen No that is not the intention. These link relations are from Allen's work. Yes, OWL-Time is an OWL ontology, but the relations are defined independently of that formalization.  I understood that the IANA registry likes either an IETF RFC or a W3C document to support the registry entries. W3C OWL-Time provides that for temporal relations.  

1. the use case is to support links between web resources that either are, or describe, things related to a temporal interval. Knowing that a lecture overlaps lunchtime might be useful information. 

2. The scope of this proposal is temporal interval relations, as shown in the figure above. As explained in the original work by Allen, this set is sufficient (sometimes in combination) to define all relationships between time intervals. 

There is a separate algebra for spatial relations which might be considered (e.g. see http://www.opengeospatial.org/standards/geosparql), but that is for another day, if at all. 

3. I don't understand this question. The proposal is not about RDF, its about temporal relations. The W3C spec happens to describe them in the context of an RDF/OWL vocabulary, but the relations have utility outside the RDF context. By putting them into the IANA registry we standardize the terminology and meaning so it can be used consistently for linking web resources.

**Comment by reschke** [comment]
The purpose of the description in the registry is to give the reader an idea about what the link relation is - so no, neither an extract of text that assumes knowledge of the spec not a diagram will work.

**Comment by algermissen** [comment]
"Knowing that a lecture overlaps lunchtime might be useful information." - Fair enough, I get that. So you are thinking about Web resource that represent 'things'[1] that *have* an interval and not only intervals as such (which was my interpretation of your intention).

So, for 'things' that are events, places, areas I see your point in why having such link relation types makes sense.

Thanks for clarifying.

Jan

[1] Hope this does not drag me into an ontological rabbit hole :-)

**Comment by dr-shorthair** [comment]
OK - rephrasing: 

- Relation Name: intervalAfter
- Description: refers to a resource associated with a time interval that ends before the beginning of the time interval associated with this resource
- Reference: [W3C OWL-Time clause 4.2.21](https://www.w3.org/TR/owl-time/#time:intervalAfter)

**Comment by algermissen** [comment]
Using 'context' would be better, IMHO:

`Description: refers to a resource associated with a time interval that ends before the beginning of the time interval associated with the context resource`

**Comment by dr-shorthair** [comment]
Rephrasing corrected:

- Relation Name: intervalAfter
- Description: refers to a resource associated with a time interval that ends before the beginning of the time interval associated with the context resource
- Reference: [W3C OWL-Time clause 4.2.21](https://www.w3.org/TR/owl-time/#time:intervalAfter)

Next steps: 
1. rinse and repeat for the full set
2. Add them to https://github.com/link-relations/registry/blob/master/link-relations.xml and make PR

Is that correct?

**Comment by mnot** [comment]
Yes.

**Comment by dr-shorthair** [comment]
Good, see #5

**Comment by mnot** [comment]
Approved and merging. This is the first time we've done a PR-to-IANA process, so please stand by...

**Comment by dret** [comment]
mirroring @algermissen's concerns, this seems a bit odd, and possibly not quite what link relations mostly are used for. @dr-shorthair responded to those concerns that "the relations are defined independently of that formalization", but that's probably true for the majority of predicates in any given ontology.
it might be interesting for @hvdsomp to have a look here, as this seems to replicate (in a much less actionable way) what RFC 7089 has been designed to do.

**Comment by dret** [comment]
in a more procedural note: shouldn't https://www.w3.org/TR/owl-time/ then have an "IANA Considerations" section that identifies the link relations that it contributes to the registry? The spec defines many more predicates, and it would be useful to understand which ones it adds to the registry, and why that selection has been chosen.

**Comment by dret** [comment]
last but not least: aren't those predicates defined in a way that's very specific to their usage within the OWL ontology? the ontology restricts their range in very specific ways, which makes sense in the strictly typed realm of that ontology. how does that translate into the link relations? isn't that something that needs to be addressed when the definition refers to the ontology, which in turn has these specific definitions that are based on the mechanics of OWL?

**Comment by mnot** [comment]
Just to set expectations here -- this repo manages the procedure of registering new link relations. The experts' job is to apply the [criteria in RFC8288](https://tools.ietf.org/html/rfc8288#section-2.1.1.1), not decide whether a link relation is useful, etc.

So while discussion and guidance is appreciated, if you want to change a community's mind about how it's using link relations, the best place to do that is in that community. The registry does *not* perform a gatekeeping function.

**Comment by dret** [comment]
On 2018-11-23 23:05, Mark Nottingham wrote:
> Just to set expectations here -- this repo manages the procedure of 
> registering new link relations. The experts' job is to apply the 
> criteria in RFC8288 
> <https://tools.ietf.org/html/rfc8288#section-2.1.1.1>, not decide 
> whether a link relation is useful, etc.

fair enough.

> So while discussion and guidance is appreciated, if you want to change a 
> community's mind about how it's using link relations, the best place to 
> do that is in that community. The registry does /not/ perform a 
> gatekeeping function.

the github link was the first and only time i saw this being brought up. 
https://www.ietf.org/mail-archive/web/link-relations/current/maillist.html 
doesn't seem to have any announcement or discussions either. where 
was/is the community discussion happening?

**Comment by dr-shorthair** [comment]
thanks for the suggestions @dret - I was unsure how to navigate this whole system, so just followed the basic instructions. Of course happy to add any additional recommended steps. No, there was no announcement on the list. There probably should have been. 

Addressing some of your specific concerns:

1. The definitions in the PR follow the pattern bashed out in the brief conversation above, which took place in September. These definitions are not at all OWL specific. The relations come from Allen's work and were known well ahead of web applications. I cited OWL-Time to satisfy the registry's requirement to have either an IETF or W3C document available which explains the relation and in this case clearly enumerates the set, rather than rely on a more discursive article in a paywalled journal ;-)  

2. Indeed, the W3C Rec does not have an IANA considerations section. The W3C Rec is more than 1 year old now. However, an IANA section would not be disruptive to the OWL content, so it might be possible to make an addendum through the SDWIG which has taken over maintenance of the documents issued through the SDWWG. I would have to check though. 

3. Yes, there are many predicates in many RDF vocabularies, and these interval relations are only a subset of the relations in OWL-Time even. However, the set proposed are relations that concern things (such as web-pages) which occur at a specified time interval (or instant) and allow temporal relationships between them to be expressed. This seemed to likely be of interest broadly.

**Comment by dr-shorthair** [comment]
Temporal interval relations were added to IANA registry at the beginning of December 2019.

**Comment by chris-little** [comment]
I assume you mean 2018-12, not in 10 months time ;-)

**Comment by dr-shorthair** [comment]
Corrected.

**Comment by dr-shorthair** [comment]
@dret I see that I closed this but had not addressed the IANA considerations issue that you raised. 

Looking in a couple of recent W3C documents that have contributed entries into IANA registries, I see these examples: 
- https://www.w3.org/TR/powder-dr/#appD 
- https://www.w3.org/TR/resource-hints/#iana-considerations 

@chris-little , @lvdbrink @tidoust should we knock this out as an addendum?

**Comment by chris-little** [comment]
@dr-shorthair @lvdbrink I am not averse and it seems a good idea, and would desirably increase exposure of the ontology.

I suppose we keep this separate from the instand/interval discussion as that would affect the normative text?

**Comment by dr-shorthair** [comment]
I have prepared an amendment to the [W3C OWL-Time recommendation](https://www.w3.org/TR/owl-time/) which [adds an IANA Considerations section](https://rawgit.com/w3c/sdw/time-iana-considerations/time/#iana-links) formally describing the link relations that were added to the IANA registry back in December 2018.

**Comment by dret** [comment]
On 2019-07-14 22:05, Simon Cox wrote:
> I have prepared an amendment to the W3C OWL-Time recommendation 
> <https://www.w3.org/TR/owl-time/> which adds an IANA Considerations 
> section 
> <https://rawgit.com/w3c/sdw/time-iana-considerations/time/#iana-links> 
> formally describing the link relations that were added to the IANA 
> registry back in December 2018.

wow, thanks! looks like this is the perfect way to do it!

**Comment by dr-shorthair** [comment]
(I also found a cut-and-paste bug which has now been fixed in the IANA registry as well.)

**Comment by mnot** [comment]
Is there anything that needs to change in the registry as of now, or can we close this issue?

Thanks,

**Comment by dr-shorthair** [comment]
OK to close
