### ISSUE TITLE
Registration Request: down

### ISSUE THREAD

**Issue by jmezic** [link-relations/registry#52]
### Relation Name

down

### Description

Refers to a child document in a hierarchy of documents. 

### Reference

https://www.rfc-editor.org/rfc/rfc8288.html

### Additional Information

Opposite of the existing `up` relation.

Instead of `up` and `down` I would have preferred the synonyms `parent` and `child`, but I see that `up` already exists - so shouldn't `down` also exist?

**Comment by jmezic** [comment]
Found this 2009 IETF draft document describing both `up` and `down` in the context of an ATOM feed, so  this isn't a new idea: https://datatracker.ietf.org/doc/html/draft-divilly-atom-hierarchy

**Comment by mnot** [comment]
Up '[r]efers to a parent document in a hierarchy of documents' -- that is a many-to-one relationship. It's not clear that `down` is compatible with that in the usage you want.

In any case, a specification document is required; 8288 defines the registry, not `down`.
