### ISSUE TITLE
Modification request: prerender

### ISSUE THREAD

**Issue by sideshowbarker** [link-relations/registry#55]
### Relation Name

prerender

### Requested Changes

The `prerender` link relation should be completely removed, because it’s not supported in the `Link` header.

### Relationship

I’m employed by the W3C and I am also a WHATWG member.

### Additional Information

See https://github.com/w3c/whatwg-coord/issues/6#issuecomment-1469119541

**Comment by mnot** [comment]
Mike, this registry is not just for the `Link` HTTP header field; it's for all link relations. Closing with no action.
