### ISSUE TITLE
Modification request: prerender

### ISSUE THREAD

**Issue by sideshowbarker** [link-relations/registry#59]
### Relation Name

prerender

### Requested Changes

1. Add a note to the **Notes** field, with this content:

    > This relation is not part of any current standard, though support for it is implemented in Blink (the engine used by Google Chrome and other Chromium-based browsers).

2. The **Reference** field should be updated to list https://www.w3.org/TR/2023/DISC-resource-hints-20230314/.

    <s>Completely remove the contents of the **Reference** field. (The current contents are “[[Resource Hints](https://www.w3.org/TR/resource-hints/)]”, but https://www.w3.org/TR/resource-hints/ now redirects to https://html.spec.whatwg.org/#linkTypes, which now does not contain any definition for the `prerender` link relation.</s>

### Relationship

I’m employed by the W3C and I am also a WHATWG member.

### Additional Information

See https://github.com/w3c/whatwg-coord/issues/6

**Comment by mnot** [comment]
Hmm, this is awkward. Has W3C really 'disappeared' the Resource Hints specification? 

It's not relevant whether the relation is 'part of any current standard' -- we just need a publicly available, reasonably stable specification. Are there no old (cool) URLs to point at?

**Comment by sideshowbarker** [comment]
> It's not relevant whether the relation is 'part of any current standard' -- we just need a publicly available, reasonably stable specification. Are there no old (cool) URLs to point at?

Yes, thanks, and sorry for not having thought it through properly earlier. The appropriate URL to cite is this one:

https://www.w3.org/TR/2023/DISC-resource-hints-20230314/

Note that, to make its status clear, that version includes the following disclaimer:

> _Publication as a Discontinued Draft implies that this document is no longer intended to advance or to be maintained. It is inappropriate to cite this document as other than abandoned work._

(And I’ve updated the issue description so it also now states https://www.w3.org/TR/2023/DISC-resource-hints-20230314/ is what should be listed in the **Reference** field.)
