### ISSUE TITLE
Registration Request: c2pa-manifest

### ISSUE THREAD

**Issue by lrosenthol** [link-relations/registry#65]
### Relation Name

c2pa-manifest

### Description

This link relation identifies the C2PA Manifest associated with the link context

### Reference

https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html#_by_link_header

**Comment by mnot** [comment]
@lrosenthol we prefer descriptions that describe a relationship between resources; eg

> identifies the C2PA Manifest associated with the link context

Would that be OK for you?

**Comment by lrosenthol** [comment]
No problem at all @mnot - let me change it above...
