### ISSUE TITLE
amphtml relation type

### ISSUE THREAD

**Issue by martinthomson** [link-relations/registry#8]
Enter the details of the link relation type below:

* Relation Name: amphtml
* Description: Used to reference alternative content that uses the AMP profile of the HTML format.
* Reference: https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml/

Any additional information (this will not be included in the registry)?

**Comment by dret** [comment]
On 2019-07-18 08:27, Martin Thomson wrote:
> Enter the details of the link relation type below:
> 
>   * Relation Name: amphtml
>   * Description: Used to reference alternative content that uses the AMP
>     profile of the HTML format.

just wondering: isn't one of the requirements of registered relation 
types to not determine the media type of the linked resource?

in other words, wouldn't that be something to be covered by an 
"alternate" link with a media type hint of the AMP media type?

**Comment by martinthomson** [comment]
This is very much not an endorsement of the design. An "alternate" relation type would work if not for the fact that AMP uses an HTML media type. That raises an interesting question about how to signal this condition properly. 

I opened this issue merely to avoid having unaccounted squatting on code points. I am not that invested in solving AMP's problems.

**Comment by mnot** [comment]
The relevant portion of 8288:

> Registered relation types MUST NOT constrain the media type of the
   link context and MUST NOT constrain the available representation
   media types of the link target.

The wording here doesn't violate the letter of this, but certainly the spirit isn't being honoured. 

OTOH the purpose of the registry is to record what's in use, and indeed this is in use. 

Has anyone talked to folks in that community about this use, and whether it would be more appropriate to use something like `alternate`? Does AMP have a media type at all?

**Comment by mnot** [comment]
@tobie could you possibly help us out here?

**Comment by tobie** [comment]
> Has anyone talked to folks in that community about this use, and whether it would be more appropriate to use something like alternate?

For existing AMP content, I think this ship has sailed. There are billions of AMP web pages in the wild and thus, I imagine, a similar number of canonical web pages linking to them. Getting even a small portion of those to link differently to their AMP representation would be a huge undertaking and wouldn't solve the necessity of documenting the existing situation for all of the other ones.

> Does AMP have a media type at all?

No. AMP sees itself as just (a subset of) HTML.

Does this help? Happy to provide additional context if that's useful and/or discuss this further.

**Comment by mnot** [comment]
Fair enough, thanks. @tobie does the description above look reasonable to you?

**Comment by tobie** [comment]
> does the description above look reasonable to you?

Absolutely. Sorry for the delay in getting back to you; I thought I had answered this.
