### ISSUE TITLE
HTML types

### ISSUE THREAD

**Issue by mnot** [link-relations/registry#9]
Catching up with some relations defined in HTML5:

---
* Relation Name: external
* Description: refers to a resource that is not part of the same site as the current context
* Reference: https://html.spec.whatwg.org/multipage/links.html#link-type-external

---

* Relation Name: modulepreload
* Description: refers to a module that the user agent is to preemptively fetch and store for use in the current context
* Reference: https://html.spec.whatwg.org/multipage/links.html#link-type-modulepreload

---

* Relation Name: noopener
* Description: indicates that any newly created top-level browsing context which results from following the link will not be an auxiliary browsing context
* Reference: https://html.spec.whatwg.org/multipage/links.html#link-type-noopener

---

* Relation Name: opener
* Description: indicates that any newly created top-level browsing context which results from following the link will be an auxiliary browsing context
* Reference: https://html.spec.whatwg.org/multipage/links.html#link-type-opener

---

@annevk, please review. I've modified the descriptions a bit to fit better into the conventions of the registry. I'm not entirely sure about noopener and opener, but I think they'll suffice.

Note that I've used the WHATWG links here; as I read [this](https://www.w3.org/blog/2019/05/w3c-and-whatwg-to-work-together-to-advance-the-open-web-platform/), they're the most up-to-date links for HTML. @wseltzer / @annevk, is that correct?

If so, we should update other links in the registry too.

**Comment by annevk** [comment]
That's correct and the descriptions seem good enough too. Also, no 5. 😊
